url: "https://recap.build"
title: "Recap"
description: "Read schemas from web service, databases, and schema registries in a standard format."
theme: just-the-docs

logo: "/assets/images/recap-logo.png"
color_scheme: recap
aux_links:
  "<i class=\"social-logo fa-brands fa-github\"></i>":
    - "//github.com/recap-build/recap"
plugins:
  - jekyll-redirect-from

# Footer "Edit this page on GitHub" link text
gh_edit_link: true
gh_edit_link_text: "Edit this page on GitHub."
gh_edit_repository: "https://github.com/recap-build/recap-website"
gh_edit_branch: "main"
gh_edit_view_mode: "tree"

# Back to top button
back_to_top: true
back_to_top_text: "Back to top"

# Remove .html from pages
permalink: pretty
